[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 注意：我们现在通过 conftest.py 自行生成报告，不再依赖 Allure
addopts = -v -s

filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
