[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 注意：我们现在通过 conftest.py 自行生成报告，不再依赖 Allure
addopts = -v -s

markers =
    profile_account: Profile Account 模块相关测试
    financial_account: Financial Account 模块相关测试
    update_api: 更新类接口测试
    list_api: 列表查询接口测试
    detail_api: 详情查询接口测试

filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
